# Site variables
title:       Web Chess
description: This is a beautiful chess platform for chess lovers and friends.

url:         'www.weitungchen.com' # remote url  (github/website url)
# url:         'localhost:4000' # local url

baseUrl:     '/web-chess' # local baseUrl (github repo name)
# baseUrl:     '' # local baseUrl

# Build settings
markdown: kramdown
theme:    minima
